"""Extra Coach Lasso phrasing (part 1: player notes, team talks, profiles).

Merged into the pools in fcapp/lasso.py at import time, so every pool is
about five times its original size and repeats are rarer. Placeholders match
the pool each list is added to; tests in fcapp/phrase_check.py verify that
every line formats.
"""

OPENERS = {
    "Top 10%": [
        "{name}, a {r} against {opp}. I'm gonna need a minute. Somebody hand me a tissue and a clipboard.",
        "Well, slap my knee and call me a fiddle, {name}. A {r}. That's top-ten-percent {pos} stuff.",
        "{name}, a {r}. If that performance were a pie, I'd enter it in the county fair and win a ribbon.",
        "Sweet tea and sunshine, {name}. A {r} against {opp} is top 10% for any {pos} out there.",
        "{name}, I've coached a lot of games, and a {r} like that one still gives me goosebumps.",
        "Holy guacamole, {name}. A {r}. That's the kind of night that ends up on a refrigerator.",
        "A {r} from you against {opp}, {name}. Folks are gonna ask where you learned that. Tell 'em practice.",
        "{name}, a {r}. That's not a performance, that's a postcard from the top of the mountain.",
        "Ring the bell, {name}. A {r} puts you in rare air for a {pos}. Top ten percent, baby.",
        "{name}, a {r} against {opp}. I'd hug you, but I'd probably cry on your jersey.",
        "Well I'll be. {name}, a {r}. You played like the main character tonight.",
        "{name}, if I could bottle that {r}, I'd sell it at every gas station from here to Wichita.",
        "Lord have mercy, {name}. A {r} as a {pos}? That's top-ten-percent, and it's all you.",
        "{name}, a {r} against {opp}. The other team's gonna be talking about you on the drive home.",
        "Mercy me, {name}. A {r}. That one goes in the scrapbook, page one.",
        "{name}, you just put up a {r}. My heart's doing a little two-step right now.",
        "A {r}, {name}. That's the sort of game that makes the whole locker room stand a little taller.",
        "{name}, a {r} is top-ten-percent football for a {pos}. You should be proud as a peacock.",
        "Hot diggity, {name}. A {r} against {opp}. I didn't know a {pos} could do some of that.",
        "{name}, a {r}. I'm officially out of superlatives, and I keep a lot of 'em in my pocket.",
    ],
    "Top 25%": [
        "{name}, a {r}. That's top-quarter work for a {pos}, and you made it look like Sunday brunch.",
        "Look at you, {name}. A {r} against {opp}. That's the good stuff.",
        "{name}, a {r} puts you in the top 25% of {pos}s. Keep stacking those like pancakes.",
        "That's a {r}, {name}. Steady, sharp and smarter than a whip. Top quarter of {pos}s.",
        "{name}, a {r} against {opp}. You were a problem for them all night, the good kind.",
        "Well butter my cornbread, {name}. A {r}. That's a top-quarter showing.",
        "{name}, a {r}. You played like someone who read the playbook twice and highlighted it.",
        "A {r} from {name}. That's top-25% {pos} work and I want more of it.",
        "{name}, a {r}. That's what showing up looks like, and it looks good on you.",
        "{name}, a {r} against {opp}. If football were a garden, you'd be the tomatoes.",
        "Nice going, {name}. A {r} is top-quarter territory, and you didn't need a map to get there.",
        "{name}, you put up a {r}. That's the kind of number a coach writes down in pen.",
        "A {r}, {name}. You were the steady hand on the wheel tonight.",
        "{name}, a {r} against {opp}. I'd give that a gold star if I could find my sticker book.",
        "Top quarter of {pos}s with a {r}, {name}. That's no accident; that's habits.",
        "{name}, a {r}. You played with your head up and your heart out. Love to see it.",
        "{name}, that {r} was a big ol' slice of good football.",
        "A {r} against {opp}, {name}. You made the hard things look ordinary, and that's a compliment.",
        "{name}, a {r}. If confidence were contagious, you just gave the whole team a cold.",
        "Top 25% with a {r}, {name}. That's the kind of consistency championships are built on.",
    ],
    "Above average": [
        "{name}, a {r} against {opp}. A good honest shift, like a well-made chair.",
        "Solid as a fence post, {name}. A {r} is above par for a {pos}.",
        "{name}, a {r}. Not flashy, just useful, and useful wins matches.",
        "A {r}, {name}. You did your job and then some. That's the kind of teammate folks want.",
        "{name}, a {r} against {opp}. You're on the right road. Let's find the passing lane.",
        "{name}, a {r} is a good day. Not a great one yet, but good is the step before great.",
        "A {r} from {name}. Above average for a {pos}, and I can see the next gear from here.",
        "{name}, a {r}. Like a good casserole, it's not fancy, but everybody's glad it showed up.",
        "{name}, that {r} was a sturdy day's work. Proud of you.",
        "A {r} against {opp}, {name}. Good bones. Now let's hang some pictures on 'em.",
        "{name}, a {r}. You were reliable as a porch light, and that matters more than you know.",
        "{name}, a {r} for a {pos}. Better than most. Not your ceiling, though, not by a long shot.",
        "A {r}, {name}. That's a B-plus kind of day, and I happen to love B-plus days.",
        "{name}, you posted a {r} against {opp}. Keep doing the simple things this well.",
        "{name}, a {r}. Good enough to be proud of, close enough to great to be hungry.",
        "A {r} from you, {name}. Steady hands, clear head. We'll build on that.",
        "{name}, a {r}. That's what I call putting a quarter in the jukebox and getting a good song.",
        "{name}, a {r} against {opp}. You're trending up like a hot-air balloon at the fair.",
        "A {r}, {name}. You did the little things, and the little things added up.",
        "{name}, a {r} is above the line for a {pos}. Let's go hunting for the extra half point.",
    ],
    "Below average": [
        "{name}, a {r} against {opp}. Not your day, partner, but days are short and seasons are long.",
        "{name}, a {r}. A little below the line for a {pos}. We'll get you back above it.",
        "A {r}, {name}. Even the best barbecue gets a little charred sometimes.",
        "{name}, a {r} against {opp}. You battled, and battling's the part you can always control.",
        "{name}, a {r} is a quiet night. Quiet nights are where we learn to be loud.",
        "{name}, a {r}. I've seen you do better, which is exactly why I'm not worried.",
        "A {r}, {name}. That's a speed bump, not a wall.",
        "{name}, a {r} against {opp}. Little rusty. Nothing a few good reps can't polish.",
        "{name}, a {r}. Don't let it rent space in your head. Charge it a fee and move on.",
        "A {r} from {name}. Below par for a {pos}, but par is just a number on a scorecard.",
        "{name}, a {r}. Every player's got a few of these. The good ones learn from 'em fast.",
        "{name}, a {r} against {opp}. You were close to a good one. Let's find the missing piece.",
        "A {r}, {name}. It's okay to be frustrated. It's not okay to stay frustrated.",
        "{name}, a {r}. Think of it like a flat tire. Annoying, fixable, and we've got a spare.",
        "{name}, a {r} for a {pos}. A little under, a little lesson, a lot of upside.",
        "A {r} against {opp}, {name}. Not the movie we wanted, but there's a sequel tomorrow.",
        "{name}, a {r}. I'd rather you have this night now than in a playoff.",
        "{name}, a {r}. You've got more in the tank, and we're gonna go find it together.",
        "A {r}, {name}. The scoreboard says meh. I say we're one tweak away.",
        "{name}, a {r} against {opp}. Shake it off like a dog after a bath and go again.",
    ],
    "Bottom 25%": [
        "{name}, a {r} against {opp}. Rough one. Let's talk about it like grown-ups and then let it go.",
        "{name}, a {r}. Every great player has a night like this in their pocket. This is yours.",
        "A {r}, {name}. It stings. That sting means you care, and caring's half the battle.",
        "{name}, a {r} against {opp}. Tomorrow's a clean sheet of paper, and I've got a fresh pencil.",
        "{name}, a {r}. One bad night doesn't make a bad player. It makes a story you'll tell later.",
        "A {r}, {name}. We all get knocked down. The trick is getting up a little smarter.",
        "{name}, a {r}. I believe in you just as much as I did this morning. Maybe more.",
        "{name}, a {r} against {opp}. Football's a long road, and this was a pothole.",
        "A {r} from {name}. Tough day at the office. Leave it at the office.",
        "{name}, a {r}. You know what they say about rock bottom: it makes a sturdy floor to build on.",
        "{name}, a {r} against {opp}. I'm not mad. I'm motivated, and I need you motivated too.",
        "A {r}, {name}. Breathe. We'll look at the tape, find one thing, and fix it.",
        "{name}, a {r}. If you ever wonder whether I've got your back, the answer is always.",
        "{name}, a {r} against {opp}. Hard nights build hard players. Soft hearts, hard players.",
        "A {r}, {name}. That's a page, not the book.",
        "{name}, a {r}. Go easy on yourself tonight; tomorrow we roll up our sleeves.",
        "{name}, a {r} against {opp}. The comeback story starts on nights exactly like this one.",
        "A {r} from you, {name}. Bad day, good person, bright future.",
        "{name}, a {r}. We'll be curious about it, not cruel about it.",
        "{name}, a {r}. Every oak was an acorn that got rained on. Let's grow.",
    ],
}

GOOD = {
    "goal_threat": [
        "Ball in the net, smile on my face. That's the deal.",
        "That's the sound of the scoreboard saying thank you.",
        "You finished it like the last bite of a good steak.",
        "Defenders can draw up all the plans they want; you just scored anyway.",
        "Goals are the sweet tea of football, and you poured a glass.",
        "You found the corner like it owed you rent.",
        "Somebody check the net for scorch marks.",
        "That's a striker's instinct, and you can't teach that at a clinic.",
        "Cool head, quick feet, ball in the onion bag.",
        "You didn't hesitate, and the keeper didn't stand a chance.",
        "You put it where Grandma keeps the good cookies: right on the top shelf.",
        "That's how you turn a chance into a memory.",
        "The goal was open and you walked right through the door.",
        "That's what the ball's for, and you knew it.",
        "Every team needs someone who smells goals. You've got the nose.",
        "That's a finish they'll replay at the club banquet.",
        "One swing, one goal, zero doubt.",
        "Right place, right time, right foot.",
        "You treated that chance like a winning lottery ticket and cashed it.",
        "Goals change games, and you changed this one.",
    ],
    "creativity": [
        "You set the table and let everybody else eat.",
        "That's a pass with a bow on it.",
        "You see the field like a hawk sees a cornfield.",
        "You made your teammates look like heroes. That's real leadership.",
        "Chance creation is generosity with a soccer ball.",
        "You were the playmaker, the matchmaker and the good-time maker.",
        "That pass had more vision than a lighthouse.",
        "You found gaps I didn't know were there, and I was looking.",
        "Assists don't make headlines, but they make teams.",
        "You played the pass before the defense knew it was a possibility.",
        "Every key pass is a love letter to a teammate.",
        "You're the reason the forwards have something to celebrate.",
        "That's the kind of creativity that keeps opposing coaches up at night.",
        "You threaded the needle and stitched up a chance.",
        "Making chances is a gift, and you were Santa Claus tonight.",
        "You turned nothing into something more than once.",
        "Your passes had GPS and good manners.",
        "You're the opener on the team's toolbelt.",
        "That's playmaking, plain and simple.",
        "Somebody's gonna owe you dinner for those passes.",
    ],
    "passing_accuracy": [
        "You took care of the ball like it was a newborn kitten.",
        "Short, sharp and right to feet. Textbook.",
        "Your passes were cleaner than a Sunday shirt.",
        "You kept us calm by keeping the ball.",
        "That's the kind of passing that tires the other team out.",
        "Every ball you played had a destination and an arrival time.",
        "You made possession look easy, and it isn't.",
        "Good passing is just good manners with your feet.",
        "You were the metronome tonight. Tick, tock, pass.",
        "That's how you starve an opponent of the ball.",
        "Not a lot of wasted touches out there. Love it.",
        "Your passes had more accuracy than a weather app.",
        "You found the open man like a dog finds the couch.",
        "Possession is a team sport, and you were captain of it.",
        "That's composure on the ball.",
        "You passed it like you meant every one.",
        "Precision like that wins tight games.",
        "You kept the ball moving like a good conversation.",
        "Simple, smart and successful. My three favorite S's.",
        "That's the kind of passing coaches put on the whiteboard.",
    ],
    "involvement": [
        "You were always available, like a good neighbor.",
        "The ball kept finding you, and that's no coincidence.",
        "You were the heartbeat in the middle.",
        "You touched the ball more than a kid touches a cookie jar.",
        "You showed for it every time. That's courage.",
        "Every attack seemed to have your fingerprints on it.",
        "You were the hub of the wheel.",
        "Being an outlet is a selfless job, and you did it all night.",
        "Teammates trust you with the ball, and you earned that.",
        "You were everywhere except the parking lot.",
        "That's what wanting the ball looks like.",
        "You made yourself big and available, and it paid off.",
        "You kept the engine turning over.",
        "You were in the middle of everything, like gravy on mashed potatoes.",
        "High involvement, high impact.",
        "The team ran through you, and you held up just fine.",
        "You found pockets of space like a cat finds sunbeams.",
        "You were a constant option, and options win games.",
        "That's a player who wants the responsibility.",
        "You stayed in the game every single minute.",
    ],
    "tackle_timing": [
        "You timed it like a grandfather clock.",
        "Clean win, no foul, ball's ours. Beautiful.",
        "You were patient as a fisherman, then struck.",
        "That's defending with your brain first and your boots second.",
        "Every tackle you won turned their attack into our counter.",
        "You read their touch like a newspaper.",
        "You stayed on your feet and won it anyway. That's a skill.",
        "That's defending a coach can trust.",
        "You picked their pocket and nobody even noticed.",
        "Timing like that is learned, and you've learned it.",
        "Their attackers walked into you like a screen door.",
        "Win the ball, start the attack. You did both.",
        "That's a tackle that deserves its own highlight reel.",
        "You knew exactly when to go, and you went.",
        "Clean tackles are free possession, and you handed us plenty.",
        "You defended like you were protecting the last slice of pie.",
        "You turned their best moments into our turnovers.",
        "Sharp, clean, decisive. That's how it's done.",
        "That's the kind of defending that wins matches quietly.",
        "You made their attackers think twice, then three times.",
    ],
    "defensive_work_rate": [
        "You put in a shift and then asked for overtime.",
        "Effort like that is contagious, and I hope everybody caught it.",
        "You chased lost causes and found a few.",
        "You covered more ground than a mail carrier.",
        "That's grit, and grit wins tight games.",
        "You never stopped running. My legs hurt watching.",
        "The dirty work is still work, and you clocked in.",
        "You were in their faces all night, politely.",
        "You pressed like the ball owed you money.",
        "Defending is a choice, and you chose it every time.",
        "You made their midfield very uncomfortable.",
        "That kind of work rate makes everyone around you better.",
        "You didn't wait for the ball; you went and got it.",
        "You put your body on the line, and I noticed.",
        "Hustle like that doesn't show up in highlights, but it shows up in results.",
        "You were a pest, the very best kind.",
        "Work rate is the one stat you fully control, and you maxed it.",
        "You tracked back like it was your house on fire.",
        "That's a team-first performance.",
        "Effort like that earns respect in any locker room.",
    ],
    "shot_volume": [
        "You kept the keeper busier than a one-man band.",
        "Shoot your shot. You did, over and over.",
        "Volume creates chances, and you created plenty.",
        "You were hungry in front of goal, and I love a hungry striker.",
        "You made the keeper earn every dollar tonight.",
        "Shots are tickets to the goal lottery, and you bought a stack.",
        "You kept testing them until something cracked.",
        "The more you shoot, the luckier you get.",
        "You weren't shy, and shy doesn't score.",
        "You kept the pressure on like a lid on a pot.",
        "That's an attacking mindset.",
        "You got into shooting spots again and again.",
        "Their defense never got a moment of peace.",
        "Shooting is believing, and you believed.",
        "You were knocking on that door like you were selling encyclopedias.",
        "Keep finding those looks; the goals will follow.",
    ],
    "shot_selection": [
        "You picked good shots like picking ripe apples.",
        "Accuracy over ego. That's maturity.",
        "You hit the frame, and that's how you give yourself a chance.",
        "Smart shooting is half of finishing.",
        "You made every shot count for something.",
        "Patient in the box, precise with the boot.",
        "You took the good looks and passed on the bad ones.",
        "On target is the first rule of shooting club.",
        "You made the keeper make decisions, and that's the job.",
        "That's quality over quantity.",
        "Calm feet, clear head, on target.",
        "You aimed like a dart champion at the county fair.",
        "Good decisions before good finishes.",
        "You kept it low and on target. Keepers hate that.",
        "That's composure in front of goal.",
        "You were picky in the best way.",
    ],
    "finishing": [
        "Ice in the veins, honey in the heart.",
        "You finish chances like a good book: all the way to the end.",
        "That's clinical. Doctor-level clinical.",
        "You turned shots on target into goals. That's the whole recipe.",
        "Keepers just watched those go by.",
        "That's what composure looks like.",
        "Calm, cool and in the corner.",
        "Finishing like that wins titles.",
        "You made the hardest part look like the easiest part.",
        "You struck it true and it went where you told it.",
        "That's a finisher's touch.",
        "You hit the target and the target hit the net.",
        "Sharpshooter stuff.",
        "You were efficient as a hummingbird.",
        "Clinical finishing is a beautiful thing.",
        "That's how you punish a defense.",
    ],
    "shot_stopping": [
        "You were a wall, a big friendly wall.",
        "Hands like flypaper.",
        "You made saves that made their strikers question their life choices.",
        "That's goalkeeping with guts.",
        "You shut the door and locked it.",
        "Every save is a goal for the other end, and you scored plenty.",
        "You were big when it mattered.",
        "Keeper of the year, keeper of the night, keeper of my heart.",
        "You made the net look tiny.",
        "Reflexes like a cat on a hot tin roof.",
        "That's a goalkeeper who wants the ball coming at him.",
        "Their strikers are gonna dream about you, and not happily.",
        "You read shots like a bedtime story.",
        "Big saves, big presence.",
        "You kept us in it with your hands.",
        "That's how a keeper earns trust.",
    ],
    "busy_keeper": [
        "You were busier than a bee in a flower shop.",
        "They threw everything at you and you threw it back.",
        "A lot of shots, a lot of saves, a lot of heart.",
        "You held the fort when the walls were shaking.",
        "Goals against aren't all on you; the saves were all you.",
        "You stood tall under heavy fire.",
        "You kept the score respectable and our hopes alive.",
        "That was a shooting gallery and you were the bulletproof vest.",
        "The defense left the door ajar and you slammed it.",
        "You were the last line, and you held.",
        "Busy nights build great keepers.",
        "That workload would break a lesser keeper.",
    ],
    "clean_sheet": [
        "Zero conceded. My favorite number, tied with biscuits.",
        "Clean sheet, clean conscience.",
        "Nothing got through. Not a breeze, not a ball.",
        "That's a shutout, and shutouts are a team photo.",
        "You helped keep their side of the scoreboard empty.",
        "A clean sheet is a quiet thing that speaks loud.",
        "Fresh as clean laundry on a summer line.",
        "No goals against. That's defending as a family.",
        "Their strikers went home empty-handed.",
        "Clean sheets win leagues.",
        "Not a single goal allowed. That's a statement.",
        "You kept the back door locked and the porch light on.",
    ],
    "leadership": [
        "Player of the match. The trophy suits you.",
        "Man of the Match means everybody noticed, including me.",
        "That's a performance people follow.",
        "You led by example, and the example was excellent.",
        "MOTM. Put it on the fridge and the resume.",
        "When you play like that, the whole team stands taller.",
        "That's leadership you can't fake.",
        "You were the best player on the pitch, and you know it. Now stay humble.",
        "Top performer, top teammate.",
        "That's an award you earned, not one they handed you.",
        "Man of the Match: the highest compliment the game gives out.",
        "You carried the moment and carried us.",
        "Leaders make the hard moments look easy.",
        "You set the bar, now the rest of us get to chase it.",
        "That's a captain's performance, armband or not.",
        "Everybody wants to play with someone who plays like that.",
    ],
}

WORK_LEADIN = [
    "Here's a thought:", "Coach's tip:", "Tiny tweak:", "For next time:", "Quick fix:", "Try it this way:",
    "Here's the play:", "Remember this:", "My two cents:", "Lesson of the day:", "Pro tip:", "Keep this in your pocket:",
    "Small change, big gain:", "Training homework:", "Let's try:", "Think about this:", "Here's what helps:",
    "Write this down:", "A little secret:", "Next match:", "Easy win:", "Simple as pie:", "Here's the trick:",
    "Old coach's advice:", "One more thing:", "Real quick:", "Golden rule:", "Habit to build:", "Low-hanging fruit:",
    "Let's sharpen this:", "Focus point:", "From the clipboard:", "Here's the deal:", "Start here:", "Key note:",
    "Fix it like this:", "Little adjustment:", "Next rep:", "Mind this:", "Best practice:", "Easy money:",
    "Mark my words:", "Repeat after me:", "Here's how:", "Game plan:", "Bread and butter:", "Fundamentals:",
    "Back to basics:",
]

TEAMMATE_GOOD = [
    "You and {mate} had more chemistry than a high school lab.",
    "Every time you found {mate}, something good happened.",
    "You and {mate} were finishing each other's sentences out there.",
    "That link with {mate} was smoother than a Cadillac on new pavement.",
    "You and {mate} play like you've known each other since kindergarten.",
    "Feeding {mate} like that is a recipe I want to keep making.",
    "{mate} scored and you were the reason. Take a bow.",
    "You and {mate} were a two-person band and the crowd loved it.",
    "That partnership with {mate} is starting to feel like a habit.",
    "You saw {mate}'s run before {mate} did.",
    "You and {mate} turned simple passes into goals.",
    "{mate} owes you a milkshake for those passes.",
    "You and {mate} were like salt and pepper tonight. Better together.",
    "Keep finding {mate}; it's working like a charm.",
    "That connection with {mate} is gold. Don't let it rust.",
    "You and {mate} combined like peanut butter and banana. Underrated and delicious.",
    "Your passes to {mate} had perfect weight and perfect timing.",
    "{mate} finished what you started. That's teamwork.",
    "You and {mate} speak the same football language.",
    "That's a partnership I'd build a team around: you and {mate}.",
    "You set it up, {mate} knocked it down. Repeat as needed.",
    "Your vision plus {mate}'s finishing equals a very happy coach.",
    "You and {mate} were on the same page, same paragraph, same sentence.",
    "{mate} scored, but that goal had your name in the credits.",
]

TEAMMATE_WORK = [
    "You and {mate} both got caught on {issue}. Fix it together: {fix}.",
    "Same {issue} trouble for you and {mate}. Buddy up: {fix}.",
    "{mate} struggled with {issue} too. Work on it as a pair: {fix}.",
    "You and {mate} share the {issue} homework. Study group: {fix}.",
    "{issue} hit you and {mate} both. Partner drill: {fix}.",
    "You and {mate}: {issue}. Two-person fix: {fix}.",
    "Both you and {mate} dipped on {issue}. Lean on each other: {fix}.",
    "{mate} had the same {issue} gremlin. Squash it together: {fix}.",
    "You and {mate} can fix {issue} as a duo: {fix}.",
    "{issue} showed up for you and {mate}. Talk it through and {fix}.",
    "Team project for you and {mate}: {issue}. The plan: {fix}.",
    "You and {mate} both need a tune-up on {issue}. Do it together: {fix}.",
    "Funny how {issue} snagged you and {mate} both. Remedy: {fix}.",
    "Heads up, you and {mate}: {issue}. Simple fix: {fix}.",
    "You and {mate} have a shared to-do on {issue}: {fix}.",
    "Partners in crime on {issue}, you and {mate}. Partners in the fix too: {fix}.",
    "{issue} got you and {mate}. Communicate and {fix}.",
    "You and {mate} were in the same boat on {issue}. Row together: {fix}.",
    "{issue} needs work from you and {mate}. Easy plan: {fix}.",
    "You and {mate}, same lesson: {issue}. Same answer: {fix}.",
    "Pair up with {mate} on {issue}: {fix}.",
    "{mate} and you both slipped on {issue}. Catch each other: {fix}.",
    "You and {mate} need to sync up on {issue}: {fix}.",
    "{issue} is your shared homework with {mate}: {fix}.",
]

FORM_UP = [
    "{x} above your average. That's a staircase and you're climbing.",
    "{x} better than usual. The arrow is pointing straight up.",
    "{x} over your norm. Whatever you ate for breakfast, keep eating it.",
    "{x} above average. Growth looks good on you.",
    "{x} higher than your usual. That's progress you can measure.",
    "{x} up on your average. Momentum is a wonderful thing.",
    "{x} above your typical game. Keep raising your own bar.",
    "{x} better than you usually play. That's the new normal, I hope.",
    "{x} over average. You're outgrowing your old numbers.",
    "{x} above your usual. Somebody's been practicing.",
    "{x} better than your norm. I'm writing that down in pen.",
    "{x} above average. Rising like bread in a warm kitchen.",
    "{x} up on your usual. Step by step, you're getting there.",
    "{x} above your norm. That's what effort compounds into.",
    "{x} better than usual. More of this, please and thank you.",
    "{x} above your average. You're making improvement look easy.",
    "{x} over your typical rating. The work is paying off.",
    "{x} above usual. That's not luck, that's reps.",
    "{x} up on your norm. Let's make it a habit.",
    "{x} above your average. Look at you go.",
    "{x} better than usual. Proud doesn't cover it.",
    "{x} above your norm. That's a personal trend line I like.",
    "{x} above average. Your future self says thanks.",
    "{x} over your usual. Keep the elevator going up.",
]

FORM_DOWN = [
    "{x} below your average. One dip doesn't make a trend.",
    "{x} under your usual. Shake it off and lace 'em up.",
    "{x} below your norm. We'll get you back to you.",
    "{x} under average. Even good weeks have a rainy day.",
    "{x} below your typical game. Next one's the bounce-back.",
    "{x} down on your usual. A pothole, not a cliff.",
    "{x} under your norm. Let's figure out why and fix it.",
    "{x} below average. You're better than this number, and we both know it.",
    "{x} under your typical rating. Short memory, long season.",
    "{x} below usual. Every streak has a hiccup.",
    "{x} down on your average. Tomorrow's a fresh page.",
    "{x} under your norm. Rest up, reset, return.",
    "{x} below your average. Be a goldfish about it.",
    "{x} under usual. One fix and you're back on track.",
    "{x} below your typical game. That's an outlier, not an identity.",
    "{x} down on your norm. We go again.",
    "{x} below average. The fight's still in you; I saw it.",
    "{x} under your usual. Bad days are tuition for good ones.",
    "{x} below your norm. Let's turn the page.",
    "{x} under average. You'll be back above it soon enough.",
    "{x} below usual. No panic, just practice.",
    "{x} down on your average. Even the best hitters have 0-for-4 nights.",
    "{x} below your norm. Chin up, eyes forward.",
    "{x} under average. That's a blip. Blips blip.",
]

DRIVER_GOOD = [
    "{what}: +{x}. Little things, big difference.", "{what} added +{x}. Quiet contributions count.",
    "{what} was worth +{x}. Nice bonus.", "{what}: +{x} to your rating. Keep stacking those.",
    "{what} pushed you up +{x}. Good habits pay.", "{what}: +{x}. The details are doing their job.",
    "{what} earned you +{x}. Smart football.", "{what}: +{x}. That's money in the bank.",
    "{what} chipped in +{x}. Every bit helps.", "{what}: +{x}. You did the boring stuff well, and it showed.",
    "{what} gave you +{x}. Don't underestimate it.", "{what}: +{x}. Small wins add up to big ones.",
    "{what} lifted you +{x}. Like a tailwind on a bike ride.", "{what}: +{x}. Good stuff.",
    "{what} counted for +{x}. That's the hidden value in your game.", "{what}: +{x}. Steady contributions win seasons.",
    "{what} put +{x} on the board for you.", "{what}: +{x}. Coach likes this one.",
    "{what} delivered +{x}. Keep it up.", "{what}: +{x}. The fundamentals are your friend.",
    "{what} was good for +{x}. That's efficient.", "{what}: +{x}. Unsung, but sung by me.",
    "{what} nudged it up +{x}. Every inch.", "{what}: +{x}. Nice piece of business.",
    "{what} added +{x}. Like interest on savings.", "{what}: +{x}. The little extras matter.",
    "{what} bumped you +{x}. Love it.", "{what}: +{x}. Do that again.",
    "{what} gave a +{x} boost.", "{what}: +{x}. Solid foundation stuff.",
    "{what} earned +{x}. Quiet excellence.", "{what}: +{x}. That's how good ratings get built.",
    "{what} was worth +{x} all by itself.", "{what}: +{x}. Cherry on top.",
    "{what} added +{x}. Keep collecting those.", "{what}: +{x}. That's value.",
    "{what} pushed +{x}. Underrated work.", "{what}: +{x}. Nicely done.",
    "{what} lifted +{x}. Small hinge, big door.", "{what}: +{x}. Well played.",
]

DRIVER_WORK = [
    "{what}: -{x}. Easy points to win back.", "{what} cost {x}. Clean it up and you're cooking.",
    "{what} took {x} away. Fixable.", "{what}: -{x}. Let's tighten that screw.",
    "{what} docked {x}. Small leak, easy patch.", "{what}: -{x}. That's your quickest improvement.",
    "{what} cost you {x}. Next match, keep it simple.", "{what}: -{x}. Low-hanging fruit.",
    "{what} pulled {x} off. We'll get it back.", "{what}: -{x}. A little care goes a long way.",
    "{what} shaved {x}. Not a big deal, but a real one.", "{what}: -{x}. Attention to detail fixes this.",
    "{what} cost {x}. Think before the touch.", "{what}: -{x}. One habit and it's gone.",
    "{what} dropped you {x}. Let's patch that.", "{what}: -{x}. Easy fix, big payoff.",
    "{what} took {x}. Clean that up next time.", "{what}: -{x}. Practice makes permanent.",
    "{what} lost {x}. We'll drill it.", "{what}: -{x}. Slow down a hair.",
    "{what} cost {x}. Not the end of the world.", "{what}: -{x}. Next rep, better rep.",
    "{what} knocked off {x}. Patience fixes most of it.", "{what}: -{x}. Keep it simple.",
    "{what} cost {x}. That's on the to-do list.", "{what}: -{x}. Little leaks sink big ships.",
    "{what} took {x}. Head up first, then play.", "{what}: -{x}. Easy upgrade available.",
    "{what} cost {x}. Smarter choices fix it.", "{what}: -{x}. Let's not make it a habit.",
    "{what} took {x}. Focus on the next one.", "{what}: -{x}. Tidy that up.",
    "{what} cost {x}. One thing at a time.", "{what}: -{x}. Next match, nail it.",
    "{what} dropped {x}. Simple fix.", "{what}: -{x}. Don't sweat it, fix it.",
    "{what} cost {x}. Learn and move on.", "{what}: -{x}. Room to grow.",
    "{what} took {x}. Better decisions, better rating.", "{what}: -{x}. Let's polish that.",
]

BENCHMARK = [
    "{label}: {val}. Top-quarter {role}s live at {target}+. Let's move in.",
    "{label}: {val}. The good neighborhood starts at {target}+.",
    "{label}: {val}. Solid, but the best {role}s hit {target}+.",
    "{label}: {val}. A few steps from the {target}+ club.",
    "{label}: {val}. Top {role}s reach {target}+. You've got the legs for it.",
    "{label}: {val}. Middle of the road; {target}+ is the fast lane.",
    "{label}: {val}. Push for {target}+ and you're elite company.",
    "{label}: {val}. Good. Great starts at {target}+.",
    "{label}: {val}. The bar for top {role}s is {target}+. Go clear it.",
    "{label}: {val}. Halfway to the summit; the peak is {target}+.",
    "{label}: {val}. {target}+ is where top {role}s hang their hats.",
    "{label}: {val}. You're in the conversation. {target}+ wins the argument.",
    "{label}: {val}. Next target: {target}+.",
    "{label}: {val}. One gear up gets you to {target}+.",
    "{label}: {val}. Nice base. Build to {target}+.",
    "{label}: {val}. {target}+ is the gold standard for a {role}.",
    "{label}: {val}. Climb to {target}+ and you're top quarter.",
    "{label}: {val}. Average-plus; top {role}s are at {target}+.",
    "{label}: {val}. Keep pushing; {target}+ is within reach.",
    "{label}: {val}. A good number on the way to {target}+.",
    "{label}: {val}. Top tier {role}s post {target}+. Let's join 'em.",
    "{label}: {val}. You're knocking on the {target}+ door.",
    "{label}: {val}. The next level is {target}+.",
    "{label}: {val}. Good foundation, {target}+ ceiling.",
    "{label}: {val}. Raise it to {target}+ and you're a difference maker.",
    "{label}: {val}. {target}+ is where the magic lives.",
    "{label}: {val}. Steady. Elite {role}s get to {target}+.",
    "{label}: {val}. A little more and you're in the {target}+ crowd.",
    "{label}: {val}. Don't settle; {target}+ is there for the taking.",
    "{label}: {val}. Mid-pack today, {target}+ tomorrow.",
    "{label}: {val}. Aim for {target}+.",
    "{label}: {val}. Let's make {target}+ the habit.",
]

TEAM_W = [
    "We beat {opp} {score}. Wins are better when they're shared.",
    "{score} over {opp}. That's a good night's work.",
    "Win against {opp}, {score}. Somebody cue the music.",
    "{score} win. Three points in the cupboard.",
    "Took care of {opp} {score}. Proud of the group.",
    "{score} over {opp}. That's what happens when we play together.",
    "We got the W against {opp}, {score}. Savor it.",
    "{score} win over {opp}. Biscuits for everybody.",
    "Beat {opp} {score}. That's a team that believes.",
    "{score} against {opp}. A win's a win, and this was a good one.",
    "Win, {score}, over {opp}. Keep the streak breathing.",
    "{score} over {opp}. Points banked, smiles earned.",
    "We handled {opp}, {score}. Business done.",
    "{score} win. The locker room's gonna be loud.",
    "Beat {opp} {score}. That's how you write a happy ending.",
    "{score} over {opp}. Collective effort, collective win.",
    "Won {score} against {opp}. Feel good about it tonight.",
    "{score} win over {opp}. We were the better team, and it showed.",
    "Another W: {score} over {opp}.",
    "{score} against {opp}. Winners, plain and simple.",
    "Took {opp} down {score}. That's growth.",
    "{score} over {opp}. Make it a habit.",
    "We beat {opp} {score}. Sweet as pecan pie.",
    "{score} win. Enjoy it, then get ready for the next one.",
]

TEAM_D = [
    "{score} with {opp}. Half the points, all the lessons.",
    "Drew {score} with {opp}. Close, but not quite.",
    "{score} against {opp}. We'll take the point and the notes.",
    "Level at {score} with {opp}. Stalemates teach patience.",
    "{score} draw. Neither team blinked.",
    "Drew {score} with {opp}. A point is better than none.",
    "{score} with {opp}. We left a little on the table.",
    "Even at {score} with {opp}. Let's find the winner next time.",
    "{score} against {opp}. Honest result, honest effort.",
    "Shared the points at {score}. Tomorrow we take all three.",
    "{score} with {opp}. Not bad, not great, very fixable.",
    "Draw, {score}. A coin flip we didn't lose.",
    "{score} with {opp}. We'll sharpen the edges.",
    "Drew {score}. The win was right there; let's go grab it next time.",
    "{score} with {opp}. Respectable, with room to grow.",
    "Level, {score}, with {opp}. Learn from it and move on.",
]

TEAM_L = [
    "Lost {score} to {opp}. Learn it, leave it.",
    "{score} to {opp}. We'll come back stronger.",
    "Fell {score} to {opp}. Tomorrow's a better story.",
    "{score} loss. Lessons are the consolation prize.",
    "{opp} got us {score}. Heads up, eyes forward.",
    "Lost {score}. It stings, and stings fade.",
    "{score} to {opp}. Not our night. Our nights are coming.",
    "Dropped one to {opp}, {score}. Back to work.",
    "{score} loss to {opp}. Every setback sets up a comeback.",
    "Lost to {opp} {score}. We'll study it, then forget it.",
    "{score} to {opp}. Bruised, not broken.",
    "Fell to {opp} {score}. Fuel for next time.",
    "{score} loss. The scoreboard won this round.",
    "Lost {score} to {opp}. Chins up, cleats on.",
    "{score} to {opp}. One loss, many matches left.",
    "Beaten {score} by {opp}. Let's use it.",
    "{score} loss. We'll get 'em next time.",
    "Lost to {opp}, {score}. A bump in the road.",
    "{score} to {opp}. Tough pill, good medicine.",
    "Fell {score}. Get some rest; we go again.",
    "{score} to {opp}. A lesson wrapped in a loss.",
    "Lost {score}. The comeback starts now.",
    "{score} to {opp}. Not the result, but not the end.",
    "Dropped it {score} to {opp}. Be a goldfish.",
]

CAREER_HIGH = [
    "{r} is your best rating in {n} matches. Frame it.",
    "Career night: {r}, the top mark of your {n} matches with us.",
    "A {r} beats every one of your previous {n} games. New high water mark.",
    "Personal best, {r}. Somebody fetch the confetti.",
    "{r} sets a new bar for you across {n} matches.",
    "Best rating of your time with us: {r}.",
    "A new personal record at {r}. That's growth you can hold.",
    "{r} tops all {n} of your matches. Remember how this felt.",
    "That {r} is your ceiling now. Let's raise it again.",
    "Highest rating yet: {r}. History made.",
    "{r}: a career best over {n} games.",
    "Your best game for us yet, {r}. I'm grinning ear to ear.",
]

BAND_LINE = [
    "A {r} sits in the {band} of {role}s.", "League-wide, {r} is {band} for a {role}.",
    "{r}: {band} among {role}s.", "That {r} ranks {band} across all {role}s.",
    "Stack {r} against every {role}: {band}.", "{band} of {role}s with a {r}. Nice company.",
    "A {r} puts you {band} for a {role}.", "{r} is {band} stuff for any {role}.",
    "Among {role}s, {r} is {band}.", "{r}. That's {band} football for a {role}.",
    "Compared to every {role} out there, {r} is {band}.", "{band} {role} performance at {r}.",
    "{r} lands you in the {band} of {role}s.", "A {r} is {band} territory for a {role}.",
    "By the numbers, {r} is {band} for a {role}.", "{r}: {band}. Elite neighborhood.",
    "{band} among {role}s league-wide with a {r}.", "{r} for a {role}? {band}.",
    "That {r} is {band} for a {role}, no question.", "{r} is a {band} {role} number.",
    "League-wide {band}, {r}.", "You hit {r}, {band} for a {role}.",
    "{r} keeps you {band} among {role}s.",
]

MINUTES = [
    "Played all {mins} minutes. Iron lungs.", "{mins} minutes logged. Durability is a skill.",
    "Full {mins}-minute shift. Thank you.", "{mins} minutes on the clock. Every one counted.",
    "Went the full {mins}. Reliable as sunrise.", "{mins} minutes of effort. I noticed.",
    "{mins} minutes, start to finish.", "Put in {mins} minutes. That's commitment.",
    "{mins} minutes and still running at the end.", "Gave us {mins} minutes. Grateful.",
    "{mins} minutes of being available.", "{mins} minutes, no breaks, no excuses.",
    "Logged {mins} minutes like a pro.", "{mins} minutes played. Stamina is underrated.",
    "{mins} full minutes. You showed up.", "{mins} minutes and you never hid.",
    "{mins} minutes. The definition of dependable.", "Played the full {mins}. That matters.",
    "{mins} minutes in the tank.", "{mins} minutes of honest work.",
    "Every one of {mins} minutes, you were there.", "{mins} minutes. Good legs.",
    "{mins} minutes on the pitch, zero quit.",
]

ONE_THING = [
    "Pick one thing above. Just one. Make it yours.", "Don't fix everything. Fix one thing really well.",
    "Choose a single focus for next match.", "One habit at a time. That's how champions are built.",
    "Circle one item and own it.", "Small steps beat giant leaps.",
    "Pick your favorite fix and run with it.", "Start with one. The rest follows.",
    "One improvement per match adds up fast.", "Focus beats frenzy. Pick one.",
    "Make one thing automatic, then pick the next.", "Don't overload the cart. One item.",
    "Take one lesson to the next game.", "Pick one, practice it, master it.",
    "One target, full attention.", "Choose one and give it your all.",
    "Better at one thing beats okay at five.", "One bite at a time.",
    "Lock in on one fix.", "Simplify: one goal for next match.",
    "Pick the easiest one and win it.", "One step forward, every match.",
    "Focus on one and watch the others improve.", "Choose your project.",
]

DRILL_LEAD = [
    "Drill:", "Training ground:", "Practice this:", "Homework:", "Five-minute drill:", "Before next match:",
    "Warm-up idea:", "Coach's drill:", "Rep it:", "Session plan:", "Skills corner:", "Try this in practice:",
    "Garden drill:", "Quick drill:", "Daily reps:", "Practice plan:", "Drill of the day:", "Work on:",
    "Fundamentals drill:", "Rondo time:", "Pre-match routine:", "Training note:", "Repetition station:",
    "Practice pointer:", "Teach your feet:", "Skill builder:", "Kickabout task:", "Tonight's homework:",
    "Backyard drill:", "Muscle memory:", "Practice prescription:",
]

CLOSERS_GOOD = [
    "Proud of you. Go celebrate responsibly.", "That's how it's done. More of that, please.",
    "You made my night. Thank you.", "Keep shining, superstar.", "Bring that energy back next match.",
    "I'll be smiling about that one all week.", "Good game, great person, bright future.",
    "Now go hydrate like a champion.", "That's the player I knew you were.", "Stay humble, stay hungry.",
    "Enjoy it tonight. You earned it.", "The team's lucky to have you.",
    "Keep raising the bar, I'll keep raising the clipboard.", "You make coaching fun.",
    "Hold onto this feeling.", "Let's do it again tomorrow.", "Tell your mama I said hi.",
    "That one goes in the memory bank.", "Couldn't have asked for more.", "Rest up, legend.",
    "You played with joy, and joy is contagious.", "Gold star, big hug, see you next match.",
    "Absolute delight to watch.", "You're the real deal.", "Keep being you.",
    "What a joy. What a game.", "I'm proud as a peacock.", "Biscuits are on me, again.",
    "Celebrate, then sleep.", "That's championship stuff.", "Keep that fire burning.",
    "Go put your feet up.", "That's a keeper of a performance.", "Smile; you earned it.",
    "Same time, same energy, next match.", "You're making believers out of everybody.",
    "That deserves a slow clap.", "You did good, kid. Really good.", "I'm framing this one.",
    "Keep writing those happy chapters.", "On to the next one.", "Take a bow.",
    "That's how legends start.", "You were a pleasure tonight.", "Keep the good times rolling.",
    "Stay hydrated and humble.", "Nothing but pride over here.", "Champions are made on nights like this.",
    "Thanks for making it look easy.", "Proud of you, partner.",
]

CLOSERS_MIXED = [
    "Rome wasn't built in a day; neither is a great player.", "Keep your head up and your feet moving.",
    "Mistakes are just lessons in disguise.", "We'll sharpen it at practice.", "Progress over perfection.",
    "One step at a time, partner.", "Tomorrow's a new chance.", "I believe in you, period.",
    "Learn it, then leave it.", "Every game teaches us something.", "Stay curious about your game.",
    "We're building something here.", "Good effort, better days ahead.", "Keep chipping away.",
    "Growth is messy, and that's okay.", "Hang in there; it's coming.", "Brick by brick.",
    "You're closer than you think.", "Next match, we go again.", "Trust the work.",
    "Never mind the noise; mind the next rep.", "Patience with yourself, please.",
    "Every great story has a slow chapter.", "Let the lesson stick, let the frustration go.",
    "The best is ahead of you.", "One rough patch doesn't define a field.", "Shake it off and lace up.",
    "Practice makes progress.", "Keep showing up; the results will too.", "Stay hungry, stay humble.",
    "I'm in your corner, always.", "Today's lessons are tomorrow's strengths.", "Small fixes, big changes.",
    "Keep your chin up and your effort higher.", "We'll get there together.",
    "Don't be hard on yourself; be honest with yourself.", "Hard days make strong players.",
    "Rest up and reset.", "You've got more in you. I've seen it.", "Keep believing.",
    "Better days are booked.", "Let's turn the page.", "The comeback starts now.",
    "Effort today, results tomorrow.", "We'll fix it together.", "Champions have off days too.",
    "Water the plant; it'll grow.", "Every rep counts.", "On to the next one.",
    "Keep the faith, partner.",
]

TALK_OPEN = {
    "W": [
        "Three points against {opp}, {gf}-{ga}. Let's talk about how.",
        "{gf}-{ga} win over {opp}. Pull up a chair.",
        "We beat {opp} {gf}-{ga}. Somebody open the snacks.",
        "That's a W, {gf}-{ga}, over {opp}. Proud of y'all.",
        "{gf}-{ga} against {opp}. Winning feels good, doesn't it?",
        "Victory over {opp}, {gf}-{ga}. Gather round.",
        "{opp} {ga}, us {gf}. I like that math.",
        "{gf}-{ga} win. Let's look at what went right.",
        "We took {opp} {gf}-{ga}. Happy coach, happy team.",
        "Three more points: {gf}-{ga} over {opp}.",
        "{gf}-{ga} against {opp}. That's how we do it.",
        "Beat {opp} {gf}-{ga}. Let's break it down.",
        "{gf}-{ga} and three points against {opp}. Grab a seat.",
        "W over {opp}, {gf}-{ga}. Biscuits, then breakdown.",
        "{gf}-{ga}. {opp} gave us a game and we gave 'em a lesson.",
        "That's a win over {opp}, {gf}-{ga}. Here's what I saw.",
        "{gf}-{ga}. We showed up against {opp}.",
        "{opp} is heading home with nothing. {gf}-{ga}.",
        "Win secured: {gf}-{ga} over {opp}.",
        "{gf}-{ga} over {opp}. Let's keep this train rolling.",
        "Good win over {opp}, {gf}-{ga}. Talk time.",
        "We got {opp}, {gf}-{ga}. I'm all smiles.",
        "{gf}-{ga} win against {opp}. The good guys won.",
        "{gf}-{ga} over {opp}. Let me tell you what I loved.",
    ],
    "D": [
        "{gf}-{ga} with {opp}. Let's figure out the missing goal.",
        "Drew {opp} {gf}-{ga}. Close only counts in horseshoes, but we'll take the point.",
        "{gf}-{ga} draw. Some good, some to fix.",
        "Level with {opp}, {gf}-{ga}. Gather round.",
        "{gf}-{ga} against {opp}. Even-steven.",
        "Shared points with {opp} at {gf}-{ga}.",
        "{gf}-{ga} with {opp}. The win was right there.",
        "Drew {gf}-{ga}. Let's find the extra gear.",
        "{gf}-{ga}. A point banked against {opp}.",
        "{opp} and us, {gf}-{ga}. Let's talk.",
        "{gf}-{ga} draw with {opp}. Honest result.",
        "We split it with {opp}, {gf}-{ga}.",
        "{gf}-{ga}. Not a loss, not yet a win.",
        "Tied {opp} {gf}-{ga}. Here's what I saw.",
        "{gf}-{ga} with {opp}. Half a pie, still pie.",
        "Draw against {opp}, {gf}-{ga}. Let's learn.",
    ],
    "L": [
        "{gf}-{ga} loss to {opp}. Let's learn and move on.",
        "{opp} beat us {ga}-{gf}. Gather round, no heads down.",
        "Lost to {opp}, {gf}-{ga}. Here's the honest truth.",
        "{gf}-{ga}. Not our night against {opp}.",
        "{opp} got the better of us, {ga}-{gf}.",
        "{gf}-{ga} loss. Let's talk about it calmly.",
        "Fell {gf}-{ga} to {opp}. Lessons time.",
        "{ga}-{gf} to {opp}. We'll be better for it.",
        "Loss to {opp}, {gf}-{ga}. Breathe, then listen.",
        "{gf}-{ga}. {opp} earned it. We'll earn the next one.",
        "Dropped one to {opp}, {gf}-{ga}.",
        "{gf}-{ga} loss. Be a goldfish, after we learn.",
        "{opp} won {ga}-{gf}. Let's break it down.",
        "{gf}-{ga} to {opp}. Bruised egos heal.",
        "Lost {gf}-{ga}. Chins up, here's the plan.",
        "{gf}-{ga} loss to {opp}. Fuel for the fire.",
        "{opp} {ga}, us {gf}. Not the math we wanted.",
        "{gf}-{ga}. We'll get {opp} next time.",
        "A {gf}-{ga} loss. Let's grow from it.",
        "{gf}-{ga} to {opp}. Tough one. Talk time.",
    ],
}

TALK_SIGNOFF = [
    "Believe, y'all.", "Proud of every one of you.", "Go get some rest.", "Hydrate and celebrate.",
    "See you at the next one.", "Keep the faith.", "Love you guys.", "Stay hungry.", "Onward and upward.",
    "Team first, always.", "Heads up, hearts full.", "Biscuits tomorrow.", "Proud coach here.",
    "Let's keep building.", "Good night, champs.", "Keep believing.", "One team, one goal.", "Rest those legs.",
    "Back at it tomorrow.", "Stay curious.", "Together we go.", "That's all, folks.", "Go Rips.",
    "Grizzly strong.", "Chins up, cleats on.", "Proud of the fight.", "Smiles all around.", "Keep climbing.",
    "Same time next match.", "Enjoy the night.", "Brick by brick.", "Thank you, team.", "Let's ride.",
    "Big hugs.", "Rest, reset, return.", "We go again.", "Love the effort.", "Keep that fire lit.",
    "Next one's ours.", "Proud as punch.",
]

TALK_GOOD = {
    "clean_sheet": [
        "Kept {opp} off the board. That's teamwork.", "Zero goals for {opp}. Shut the door, locked it.",
        "Clean sheet against {opp}. Everybody defended.", "{opp} couldn't find a way through. Beautiful.",
        "No goals conceded to {opp}. That's a family effort.", "Shutout over {opp}. Brick wall defending.",
        "{opp} left empty-handed. Defending as one.", "A clean sheet against {opp}. Clean as a whistle.",
        "We didn't give {opp} an inch.", "Not a single goal for {opp}. That's discipline.",
        "{opp} got nothing. Love it.", "Clean sheet vs {opp}. The whole team earned that.",
    ],
    "scoring": [
        "{gf} goals from {shots} shots. That's an attack with intent.", "Scored {gf} against {opp}. Firepower.",
        "{gf} goals. Our forwards were feeling it.", "Put {gf} past {opp}. Net-busting stuff.",
        "{gf} goals from {shots} attempts. Efficient.", "{gf} in the net against {opp}. Party time.",
        "We found the net {gf} times. That's a statement.", "{gf} goals. Their keeper's had a long night.",
        "Scored {gf} against {opp}. Attack was humming.", "{gf} goals on {shots} shots. Clinical team.",
        "{gf} goals. Every one a team effort.", "{opp} conceded {gf}. We were relentless.",
    ],
    "shot_acc": [
        "{acc}% of shots on target. Smart shooting.", "{on} of {shots} on frame. Accuracy wins.",
        "{on}/{shots} on target. Disciplined.", "{acc}% accuracy. We picked our spots.",
        "Hit the target {on} times out of {shots}. Precise.", "{acc}% on target. Keeper had to work.",
        "{on} of {shots} on target. That's quality.", "{acc}% of our shots tested the keeper.",
        "Accuracy at {acc}%. Good choices.", "{on}/{shots} on frame. That's how you pressure a keeper.",
        "{acc}% on target. No wasted shots.", "{on} of {shots} hit the target. Beautiful decisions.",
    ],
    "passing": [
        "{pp}% passing as a team. Possession kings.", "Team passing at {pp}%. Tidy football.",
        "{pp}% of passes completed. We kept the ball.", "{pp}% passing. Calm and collected.",
        "Passing at {pp}%. We made them chase.", "{pp}% completion. That's patience.",
        "{pp}% team passing. Smooth operators.", "{pp}% of passes on target. Composure.",
        "Kept it at {pp}%. They barely touched it.", "{pp}% passing. Textbook.",
        "{pp}% completion rate. We were in charge.", "{pp}% team passing. Crisp.",
    ],
    "duels": [
        "{tm} of {ta} tackles won. Tough team.", "{tp}% tackle success. We won our battles.",
        "Won {tm}/{ta} duels. Hungry for it.", "{tp}% of tackles won. Grit.",
        "{tm} of {ta} tackles won. First to every ball.", "{tp}% success in the tackle. Fierce.",
        "{tm}/{ta} won. We dominated the duels.", "{tp}% tackles won. Defending with purpose.",
        "Won {tm} of {ta} challenges. That's commitment.", "{tp}% won. We wanted it more.",
        "{tm} of {ta} tackles. Bite and timing.", "{tp}% tackle success. Physical and smart.",
    ],
    "chances": [
        "{kp} key passes. Generous football.", "Created {kp} chances. Teammates making teammates better.",
        "{kp} key passes. Vision everywhere.", "{kp} chances made. The table was set.",
        "{kp} key passes. Creativity flowing.", "We made {kp} chances. Unselfish.",
        "{kp} key passes. Playmakers all over.", "Created {kp} chances. Love the sharing.",
        "{kp} chances set up. That's team football.", "{kp} key passes. Everybody looked for the next guy.",
        "{kp} chances. Our attack had ideas.", "{kp} key passes. Beautiful build-up.",
    ],
    "star": [
        "{name} was outstanding at {r}: {bits}.", "{name} carried us with {art} {r}: {bits}.",
        "Big night for {name}, {art} {r}: {bits}.", "{name} lit it up, {r}: {bits}.",
        "{name} was the difference: {r}, {bits}.", "Shout-out to {name}, {art} {r}: {bits}.",
        "{name} at {r}: {bits}. Star turn.", "Hats off to {name}: {r}, {bits}.",
        "{name} delivered {art} {r}: {bits}.", "{name} was our engine, {r}: {bits}.",
        "{name} at their best, {r}: {bits}.", "{name} made it happen with {art} {r}: {bits}.",
    ],
}

TALK_WORK = {
    "conceded": [
        "{ga} goals conceded. Defending starts with the forwards.", "Let in {ga}. We need to get compact.",
        "{ga} against. Track runners all the way.", "Conceded {ga}. Shape before chase.",
        "{ga} goals allowed. Communicate at the back.", "{ga} conceded. Recover faster after losing it.",
        "We gave up {ga}. Stay goal-side.", "{ga} against. Everybody defends.",
        "{ga} goals let in. Tighter between the lines.", "Conceded {ga}. Close down the shooter.",
        "{ga} against us. Defend the box like it's home.", "Let {ga} in. Second balls matter.",
    ],
    "passing": [
        "{pp}% passing. We gave the ball away too often.", "Team passing at {pp}%. Keep it simple.",
        "{pp}% completion. Scan first, then pass.", "{pp}% passing. Fewer forced balls.",
        "Passing dipped to {pp}%. Short and safe.", "{pp}%. Possession is a choice; let's choose it.",
        "{pp}% passing. Use the keeper to reset.", "Only {pp}% of passes found us. Patience.",
        "{pp}% team passing. Triangles, not hopeful balls.", "Passing at {pp}%. Weight the passes better.",
        "{pp}% completion. Body shape before the ball arrives.", "{pp}%. Recycle when nothing's on.",
    ],
    "shot_sel": [
        "{on} of {shots} on target. Better looks.", "{acc}% accuracy. Set your feet first.",
        "{on}/{shots} on frame. Central spots, please.", "{acc}% on target. Fewer hopeful shots.",
        "{on} of {shots} on target. Work it into the box.", "{acc}% accuracy. Cut it back more.",
        "Only {on} of {shots} hit the target. Patience.", "{acc}%. Pick spots, not prayers.",
        "{on}/{shots} on target. Tight angles aren't our friend.", "{acc}% on frame. Shoot with purpose.",
        "{on} of {shots}. Low and hard beats high and hopeful.", "{acc}% accuracy. Calm feet in the box.",
    ],
    "tackling": [
        "{tm} of {ta} tackles won. Stay on your feet.", "{tp}% tackle success. Jockey first.",
        "Won {tm}/{ta}. Patience in the tackle.", "{tp}% won. Wait for the heavy touch.",
        "{tm} of {ta} tackles. Delay, deny, dictate.", "{tp}% tackle rate. Fewer lunges.",
        "{tm}/{ta} won. Show them the sideline.", "{tp}% success. Time it, don't force it.",
        "Won {tm} of {ta}. Body before boot.", "{tp}% won. Contain, then pounce.",
        "{tm} of {ta}. Smarter challenges.", "{tp}% tackle success. Patience pays.",
    ],
    "few_shots": [
        "Only {shots} shots. Get into the box.", "{shots} attempts. We need more bodies forward.",
        "{shots} shots. Shoot when you see it.", "Just {shots} shots. Time those runs.",
        "{shots} shots total. Attack the near post.", "Only {shots} attempts. More boldness.",
        "{shots} shots. Find the half-spaces.", "{shots} attempts. Follow the play in.",
        "Just {shots}. Shooters shoot.", "{shots} shots. Cutbacks create chances.",
        "Only {shots} shots. Make the keeper work.", "{shots} attempts. Be brave in the final third.",
    ],
    "progression": [
        "{kp} key passes from {pa}. Look forward first.", "{pa} passes, {kp} key. More vertical.",
        "{kp} chances from {pa} passes. Find the third man.", "{pa} passes, {kp} key. Switch the play.",
        "{kp} key from {pa}. Break the lines.", "{pa} passes, only {kp} key. Be brave.",
        "{kp} key passes. Receive on the half-turn.", "{pa} passes, {kp} key. Through balls to runners.",
        "{kp} key from {pa}. Progress the ball.", "{pa} passes, {kp} key. Attack the space.",
        "{kp} of {pa} were key. Forward thinking.", "{pa} passes, {kp} key. Carry it into gaps.",
    ],
    "red": [
        "{name} saw red. Discipline matters.", "Red card for {name}. Stay on your feet.",
        "{name}'s red hurt us. No slides from behind.", "{name} was sent off. Cool heads.",
        "Down a man after {name}'s red. Recover, don't foul.", "{name} got a red. Composure.",
        "Red for {name}. Last-man tackles cost games.", "{name} off with a red. Let's avoid that.",
        "{name}'s red card. Patience in the tackle.", "Lost {name} to a red. Discipline wins.",
        "{name} was dismissed. Stay calm.", "Red card, {name}. Sprint back instead.",
    ],
}

PROFILE_INTRO = [
    "{name}, {n} matches in. Let's look at the big picture.",
    "Alright {name}, here's what {n} matches tell me.",
    "{name}, I've studied all {n} of your games. Here's the scouting report.",
    "{n} matches of you, {name}. Patterns are showing up.",
    "{name}, after {n} matches, here's who you are as a player.",
    "Let's sit down, {name}. {n} matches worth of notes.",
    "{name}, {n} games is a real sample. Here's what it says.",
    "Here's my file on you, {name}: {n} matches and counting.",
    "{name}, {n} matches. The good, the growing, the next step.",
    "{n} games played, {name}. Let's talk trends.",
    "{name}, the numbers from {n} matches don't lie, and they're mostly kind.",
    "Pull up a stool, {name}. {n} matches of tape.",
    "{name}, {n} matches in and I've got thoughts.",
    "Here's the long view, {name}, across {n} matches.",
    "{name}, {n} games is enough to see your fingerprint on this team.",
    "Let's zoom out, {name}. {n} matches.",
    "{name}, your {n}-match report card.",
    "{n} matches, {name}. Here's where you shine and where we grow.",
    "{name}, after {n} games I know your game pretty well.",
    "Big-picture time, {name}: {n} matches.",
]

THEME_LINES = {
    "improving": [
        "{rate}% overall, down to {recent}% lately. You're fixing it.",
        "It used to come up {rate}% of the time; now it's {recent}%. Progress.",
        "Down to {recent}% from {rate}%. The work is working.",
        "Improving: {recent}% recently versus {rate}% overall.",
        "{rate}% of matches, but only {recent}% lately. Keep going.",
        "Trending better: {recent}% now, {rate}% overall.",
        "From {rate}% to {recent}%. That's real improvement.",
        "{recent}% lately, down from {rate}%. Nice job.",
        "Getting better: {rate}% overall, {recent}% recently.",
        "{rate}% historically, {recent}% now. You're winning this one.",
        "Shrinking from {rate}% to {recent}%. Love the trend.",
        "Flagged {rate}% overall but just {recent}% lately. Growth.",
        "Down to {recent}% from {rate}%. Stay on it.",
        "{rate}% overall, {recent}% in your last five. Better every week.",
    ],
    "worsening": [
        "Up to {recent}% lately from {rate}% overall. Let's focus here.",
        "Creeping up: {recent}% recently versus {rate}%. Time to address it.",
        "{recent}% in your last five, {rate}% overall. Priority one.",
        "It's grown to {recent}% from {rate}%. Let's nip it.",
        "Worse lately: {recent}% versus {rate}%. We'll work on it.",
        "{rate}% overall, {recent}% recently. Red flag, small one.",
        "Rising: {recent}% now from {rate}%. Front and center.",
        "{recent}% lately. That's up from {rate}%. Our project.",
        "From {rate}% to {recent}%. Let's turn it around.",
        "Climbing to {recent}% from {rate}%. Focus here first.",
        "{recent}% of recent matches versus {rate}% overall. Let's fix it.",
        "Up from {rate}% to {recent}%. Homework assigned.",
        "{rate}% overall, but {recent}% lately. Attention needed.",
        "Trending the wrong way: {recent}% vs {rate}%.",
    ],
    "steady": [
        "Steady at about {rate}% of matches. A habit to break.",
        "{rate}% overall, {recent}% lately. Consistent, and fixable.",
        "Holding at {rate}%. Let's crack it.",
        "Shows up {rate}% of the time. Steady means it's a habit.",
        "About {rate}% of matches. Time to change the pattern.",
        "{rate}% and steady. Let's move the needle.",
        "Consistent at {rate}%. Targeted practice will help.",
        "{rate}% overall, same lately. Our next project.",
        "Flat at {rate}%. Let's bend that line down.",
        "{rate}% steady. One focused week could fix it.",
        "Sitting at {rate}%. Let's get it moving.",
        "Unchanged around {rate}%. Time to tackle it.",
        "{rate}% of matches. Holding pattern; let's break it.",
        "Steady {rate}%. Practice it on purpose.",
    ],
}

THEME_STRENGTH = [
    "{rate}% of your matches. Signature move.", "There {rate}% of the time. Reliable as rain.",
    "{rate}% of matches. Build around it.", "Shows up {rate}% of the time. That's identity.",
    "{rate}% of your games. Teammates count on it.", "{rate}% consistency. That's who you are.",
    "Present in {rate}% of matches. Keep leaning on it.", "{rate}% of the time. A real weapon.",
    "{rate}% of matches. Your calling card.", "{rate}% consistency. Bankable.",
    "There {rate}% of the time. That's a strength.", "{rate}% of games. Never lose it.",
    "{rate}% of your matches. Proud of this one.", "{rate}% of the time. That's your superpower.",
    "{rate}% of matches. Consistency like that wins.", "{rate}% and counting. Keep it up.",
    "{rate}% of games. The team relies on it.", "{rate}% of the time. Rock solid.",
    "{rate}% of matches. Elite habit.", "{rate}% consistency. Gold.",
]


def merge(lasso):
    """Extend the pools in fcapp.lasso in place (append-only, so existing
    phrase ids stay put)."""
    for name, extra in globals().items():
        if not name.isupper() or not hasattr(lasso, name):
            continue
        pool = getattr(lasso, name)
        if isinstance(pool, list):
            pool.extend(x for x in extra if x not in pool)
        elif isinstance(pool, dict):
            for key, lines in extra.items():
                if key in pool:
                    pool[key].extend(x for x in lines if x not in pool[key])


# ---------------------------------------------------------------- round 2
# Personal-ranking openers ({rank} = "3rd best of 14", "best game yet (of 9)"...)
RANK_OPENERS = {
    "Top 10%": [
        "{name}, a {r} against {opp}: your {rank}. Somebody alert the town crier.",
        "{name}, that {r} is your {rank}. I'm grinning like a possum eating persimmons.",
        "Your {rank}, {name}. A {r} against {opp}. That's the good stuff, bottled and labeled.",
        "{name}, a {r}. Your {rank}. That's the version of you I tell my friends about.",
        "Well, saddle up and ride, {name}. A {r} is your {rank}.",
        "{name}, your {rank} with a {r} against {opp}. Hall of fame material, at least in my kitchen.",
        "A {r}, {name}. Your {rank}. If the season had a highlight reel, you're the opening scene.",
        "{name}, a {r} against {opp} is your {rank}. Pinch me, I might be dreaming.",
        "Ring the dinner bell, {name}. A {r} and your {rank}.",
        "{name}, your {rank}: a {r}. Fresh-baked-pie good.",
        "{name}, a {r}. That's your {rank}, and you earned every decimal.",
        "Your {rank}, {name}, with a {r} against {opp}. My heart's doing the two-step.",
    ],
    "Top 25%": [
        "{name}, a {r} against {opp}, your {rank}. That's a keeper.",
        "Your {rank}, {name}: a {r}. You're cooking with gas.",
        "{name}, a {r} is your {rank}. Right up there with your very best.",
        "A {r} against {opp}, {name}. Your {rank}, and it felt like it.",
        "{name}, your {rank} with a {r}. Sweet as sun tea.",
        "{name}, a {r}. That ranks as your {rank}. Proud of you, partner.",
        "Your {rank}, {name}. A {r} against {opp}, and you looked like you belonged.",
        "{name}, a {r} against {opp}: your {rank}. Let's make that a habit.",
        "A {r} from {name}, your {rank}. That's a good night's work.",
        "{name}, your {rank} at {r}. Good as gold.",
        "{name}, a {r}, your {rank}. You're trending the right way.",
        "Your {rank}, {name}. A {r}. That's the stuff.",
    ],
    "Above average": [
        "{name}, a {r} against {opp}, your {rank}. Solid as a church pew.",
        "Your {rank}, {name}: a {r}. Good day at the office.",
        "{name}, a {r} is your {rank}. Middle of your road, heading the right way.",
        "A {r} against {opp}, {name}. Your {rank}. Sturdy work.",
        "{name}, your {rank} with a {r}. We can build on that.",
        "{name}, a {r}, your {rank}. Not fireworks, but a warm campfire.",
        "Your {rank}, {name}. A {r} that did its job.",
        "{name}, a {r} against {opp} is your {rank}. Next gear's right there.",
        "A {r}, {name}, your {rank}. Steady hands.",
        "{name}, your {rank}: {r}. Good bones, partner.",
        "{name}, a {r}. That's your {rank}. Honest football.",
        "Your {rank}, {name}, with a {r}. Let's push it up the list.",
    ],
    "Below average": [
        "{name}, a {r} against {opp}, your {rank}. Little off, nothing broken.",
        "Your {rank}, {name}: a {r}. A dip, not a slide.",
        "{name}, a {r} is your {rank}. You've got better ones in you, and we've both seen 'em.",
        "A {r} against {opp}, {name}. Your {rank}. Let's find the missing piece.",
        "{name}, your {rank} with a {r}. Speed bump, not a wall.",
        "{name}, a {r}, your {rank}. Shake it off like a wet dog.",
        "Your {rank}, {name}. A {r}. Tomorrow's a better story.",
        "{name}, a {r} against {opp} is your {rank}. We'll climb back up the list.",
        "A {r}, {name}, your {rank}. Little rusty, easy to polish.",
        "{name}, your {rank}: {r}. Not your night, still your team.",
        "{name}, a {r}. That's your {rank}. One tweak away.",
        "Your {rank}, {name}, at {r}. Let's learn and move on.",
    ],
    "Bottom 25%": [
        "{name}, a {r} against {opp}, your {rank}. Rough one. Be a goldfish, keep the lesson.",
        "Your {rank}, {name}: a {r}. It stings, and stings fade.",
        "{name}, a {r} is your {rank}. One chapter, not the book.",
        "A {r} against {opp}, {name}. Your {rank}. We'll get you back.",
        "{name}, your {rank} with a {r}. Every oak got rained on once.",
        "{name}, a {r}, your {rank}. I believe in you as much as I did this morning.",
        "Your {rank}, {name}. A {r}. Bad day, good player.",
        "{name}, a {r} against {opp} is your {rank}. The comeback starts tomorrow.",
        "A {r}, {name}, your {rank}. Breathe. We'll fix one thing at a time.",
        "{name}, your {rank}: {r}. Hard nights build hard players.",
        "{name}, a {r}. That's your {rank}. Tomorrow's a clean sheet of paper.",
        "Your {rank}, {name}, at {r}. Chin up, cleats on.",
    ],
}

RANK_GOOD = [
    "That {r} is your {rank}. Put it on the fridge.", "Your {rank} ({r}). Keep stacking those.",
    "A {r} ranks as your {rank}. That's who you are on a good day.", "{r}: your {rank}. Remember how that felt.",
    "Your {rank}, at {r}. Every season needs a few of these.", "That's your {rank} with a {r}. Proud doesn't cover it.",
    "{r} goes down as your {rank}. Somebody write that down.", "A {r}, your {rank}. You're raising your own bar.",
    "Your {rank}: {r}. That's the standard now.", "{r}, your {rank}. Bottle it.",
    "That {r} sits as your {rank}. Lovely stuff.", "Your {rank} at {r}. Do it again.",
]
RANK_WORK = [
    "That {r} is your {rank}. One game, one lesson.", "Your {rank} ({r}). We'll get you back up the list.",
    "A {r} ranks as your {rank}. Not who you are, just where you were tonight.", "{r}: your {rank}. Be a goldfish about it.",
    "Your {rank}, at {r}. Let's make sure it stays near the bottom of the pile.", "That's your {rank} with a {r}. We go again.",
    "{r} goes down as your {rank}. Tomorrow writes a better line.", "A {r}, your {rank}. Short memory, long season.",
    "Your {rank}: {r}. Fixable, every bit of it.", "{r}, your {rank}. Learn it, leave it.",
    "That {r} sits as your {rank}. Next one's the bounce-back.", "Your {rank} at {r}. Chin up.",
]

# More Ted on the work-on bullets
WORK_TAIL = [
    "You've got this.", "Trust me on that one.", "Easy as pie.", "Small fix, big smile.", "Believe.",
    "That's a promise.", "Rome, day by day.", "Practice makes permanent.", "We'll get there together.",
    "No sweat, just reps.", "Like riding a bike.", "One rep at a time.", "Promise it's worth it.",
    "Little by little.", "You'll thank me later.", "That's the whole secret.", "Bread and butter.",
    "Keep it simple, keep it sweet.", "Slow is smooth, smooth is fast.", "Water the plant.",
    "Brick by brick.", "Patience, partner.", "You know you can.", "Easy money.", "Biscuits if you nail it.",
    "That's a coach's honest word.", "Simple as Sunday.", "Fix it and forget it.", "Clean it up and fly.",
    "Steady does it.", "Mind over matter.", "Feet first, then flair.", "Trust the work.", "It's coming.",
    "We'll drill it till it's dull.", "I've seen you do harder things.", "Next match, nail it.",
    "Habits beat highlights.", "You're closer than you think.", "That's how good becomes great.",
]

# A closing thought from Coach on every note (framed personally in lasso.build)
LASSOISMS = [
    "Be curious about your game, not cruel to it.",
    "A good teammate is like a good umbrella. You don't notice 'em till it rains.",
    "Taking on a challenge is a lot like riding a horse. Comfortable is overrated.",
    "The scoreboard counts goals; I count growth.",
    "Football's like a casserole. Everybody brings something.",
    "Confidence is a muscle. Today you got a rep in.",
    "You can't rush a good brisket or a good player.",
    "A bad touch is just a good touch that got lost.",
    "If you're gonna make a mistake, make it at full speed and learn it at half.",
    "Talent wins games; teammates win seasons.",
    "Hope is a plan with its shoes untied. Tie 'em.",
    "The ball doesn't know your rating. Neither should your attitude.",
    "Good passes are like good manners. Free, and people remember.",
    "Every pro was once an amateur who didn't quit.",
    "Smile at the goalkeeper. It confuses 'em.",
    "Win the next five seconds, then the next five.",
    "Nobody remembers the miss. Everybody remembers the response.",
    "Be a goldfish about mistakes and an elephant about lessons.",
    "The best ability is availability, and the second best is kindness.",
    "Pressure is a privilege. It means you're playing for something.",
    "A team that laughs together stays together. Tell a bad joke tomorrow.",
    "Fall seven times, stand up eight, then ask for the ball.",
    "The grass isn't greener on the other side; it's greener where you water it.",
    "There's no 'I' in team, but there's a 'me' if you scramble it. Don't scramble it.",
    "Your feet are only as fast as your eyes. Look first.",
    "Biscuits fix most things. Practice fixes the rest.",
    "Heart wins the fifty-fifties.",
    "Don't count the days; make the days count. Then count the goals.",
    "The comeback is always more fun than the setback.",
    "Believe it, then go do it.",
    "A coach's whistle is just a fancy way of saying 'I care.'",
    "Champions are just ordinary folks who kept showing up.",
    "The ball is round, the game is long, and you're doing just fine.",
    "If plan A doesn't work, the alphabet has 25 more letters.",
    "Quiet feet, loud heart.",
    "You miss every pass you don't make, and some you do. Make 'em anyway.",
    "Practice like you're second, play like you're first.",
    "Kindness costs nothing and wins locker rooms.",
    "Every game is a teacher. Some just grade harder.",
    "Stay humble, hustle hard, hydrate harder.",
    "The other team puts their shorts on one leg at a time too.",
    "A goal is just a pass to the net.",
    "Doubt is a guest. Don't give it the spare room.",
    "Don't be afraid of the dark. That's when the stars come out.",
    "The best time to plant a tree was yesterday. The second best is next match.",
    "Run like the ice cream truck just turned the corner.",
    "You're not behind; you're just early to your comeback.",
    "If it was easy, everybody'd be in Division 1.",
    "The ball will find the player who wants it. Want it.",
    "Believe in yourself the way your dog believes in you.",
]

# How Coach hands each player that closing thought - personal, never labelled
CLOSING_FRAMES = [
    "{name}, one more thing before you log off: {line}",
    "Hey {name}, hold onto this one: {line}",
    "{name}, something I want you to sleep on: {line}",
    "Between you and me, {name}: {line}",
    "{name}, here's what I'd tell my own kid: {line}",
    "Before you go, {name}: {line}",
    "{name}, write this on your hand if you have to: {line}",
    "Last thing, {name}. {line}",
    "{name}, my granddaddy told me this and now I'm telling you: {line}",
    "Listen here, {name}: {line}",
    "{name}, take this with you: {line}",
    "One thought for the road, {name}: {line}",
    "{name}, you already know this, but I'll say it anyway: {line}",
    "Hey, {name}. {line}",
    "{name}, from me to you: {line}",
    "Remember, {name}: {line}",
]
